#!/usr/bin/env php
<?php
	$app_root = rtrim(getenv('OPENSHIFT_REPO_DIR'),'/');
  $data_dir = rtrim(getenv('OPENSHIFT_DATA_DIR'),'/');
	$www_dir  = $data_dir.'/www';
	mkdir($www_dir, 0755);
	exec("cd $data_dir && ln -s www $app_root/php");
?>
